app/api/models.py
from app.utils import readDM, convert_to_array
from app import db
from os.path import dirname, join, realpath
import numpy as np

# Build semantic spaces
d = dirname(dirname(realpath(__file__)))
dm_dict_en, version = readDM(join(d,"static/spaces/english.dm"))

# Record language codes
language_codes = {}
language_codes["English"] = [dm_dict_en, "en"]


# Define a base model for other database tables to inherit
class Base(db.Model):

    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(
        db.DateTime,
        default=db.func.current_timestamp(),
        onupdate=db.func.current_timestamp())


class Urls(Base):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(500))
    title = db.Column(db.String(500))
    vector = db.Column(db.String(7000))
    freqs = db.Column(db.String(7000))
    snippet = db.Column(db.String(1000))
    cc = db.Column(db.Boolean)
    pod = db.Column(db.String(200))
    keyword = db.Column(db.String(200))

    def __init__(self,
                 url=None,
                 title=None,
                 vector=None,
                 freqs=None,
                 snippet=None,
                 cc=False,
                 pod=None,
                 keyword=None):
        self.url = url
        self.title = title
        self.vector = vector
        self.freqs = freqs
        self.snippet = snippet
        self.cc = cc
        self.pod = pod
        self.keyword = keyword

    def __repr__(self):
        return self.url

    @property
    def serialize(self):
        return {
            'id': self.id,
            'url': self.url,
            'title': self.title,
            'vector': self.vector,
            'freqs': self.freqs,
            'snippet': self.snippet,
            'cc': self.cc,
            'pod': self.pod,
            'keyword': self.keyword
        }


class Pods(Base):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200))
    url = db.Column(db.String(500))
    description = db.Column(db.String(1000))
    language = db.Column(db.String(100))
    DS_vector = db.Column(db.String(7000))
    word_vector = db.Column(db.String(7000))
    registered = db.Column(db.Boolean)

    def __init__(self,
                 name=None,
                 url=None,
                 description=None,
                 language=None,
                 DS_vector=None,
                 word_vector=None,
                 registered=False):
        self.name = name
        self.url = url
        self.description = description
        self.language = language

    @property
    def serialize(self):
        return {
            'name': self.name,
            'url': self.url,
            'description': self.description,
            'language': self.language,
            'DSvector': self.DS_vector,
            'wordvector': self.word_vector,
            'registered': self.registered
        }


# The urls matrix
def mk_matrix_from_db():
    print("Making URL matrix from database...")
    urls = []
    DS_M = []
    url_to_mat = {}
    mat_to_url = {}
    try:
        urls = Urls.query.all()
        print("Found", len(urls), "records...")
    except Exception:
        print("Database empty")
    if len(urls) > 0:
        c = 0
        DS_M = convert_to_array(urls[0].vector).reshape(1, 400)
        url_to_mat[urls[0].url] = c
        mat_to_url[c] = urls[0].url
        c += 1
        for u in urls[1:]:
            DS_M = np.vstack((DS_M, convert_to_array(u.vector).reshape(1,
                                                                       400)))
            url_to_mat[u.url] = c
            mat_to_url[c] = u.url
            c += 1
    return DS_M, url_to_mat, mat_to_url


# DS_M, url_to_mat, mat_to_url = mk_matrix_from_db()

# db.drop_all()
# db.create_all()

app/__init__.py
# Import flask and template operators
from flask import Flask

# Import SQLAlchemy
from flask_sqlalchemy import SQLAlchemy
from os.path import dirname,join,realpath

# Define the WSGI application object
app = Flask(__name__)

# Configurations
app.config.from_object('config')

# Define the database object which is imported
# by modules and controllers
db = SQLAlchemy(app)

# Sample HTTP error handling
#@app.errorhandler(404)
#def not_found(error):
#    return render_template('404.html'), 404

# Import a module / component using its blueprint handler variable (mod_auth)
from app.api.controllers import api as api_module
from app.pages.controllers import pages as pages_module
from app.search.controllers import search as search_module

# Register blueprint(s)
app.register_blueprint(api_module)
app.register_blueprint(pages_module)
app.register_blueprint(search_module)
# ..

# Build the database:
# This will create the database file using SQLAlchemy
db.drop_all()
db.create_all()


# Populate templates with pod info from self.txt
from app.api.models import Pods

dir_path = dirname(dirname(realpath(__file__)))
self_info_file = open(join(dir_path, "me.txt"),'r')
self_info = {}
for l in self_info_file:
    l = l.rstrip('\n')
    fields = l.split(" = ")
    self_info[fields[0]] = fields[1]
self_info_file.close()

if len(Pods.query.all()) == 0 and 'name' in self_info and 'description' in self_info and 'language' in self_info:
    self = Pods(name=self_info['name'], description=self_info['description'], language=self_info['language'])
    db.session.add(self)
    db.session.commit()

# Populate pod from CSV file. Can be commented out after first use.
from app.pod_loader import load_pods

app/api/__init__.py
#import app.api.mk_urls_csv

app/api/controllers.py
# Import flask dependencies
from flask import Blueprint, jsonify
from app.api.models import dm_dict_en, Urls, Pods
from app import db

# Define the blueprint:
api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/vectors/<word>/')
def return_vector(word):
    v = list(dm_dict_en[word])
    return jsonify(vector=v)


@api.route('/urls/')
def return_urls():
    return jsonify(json_list=[i.serialize for i in Urls.query.all()])


@api.route('/pods/')
def return_pods():
    return jsonify(json_list=[p.serialize for p in Pods.query.all()])


@api.route('/pods/<pod>/')
def return_pod(pod):
    pod = pod.replace('+', ' ')
    p = db.session.query(Pods).filter_by(name=pod).first()
    return jsonify(p.serialize)

app/pages/controllers.py
# Import flask dependencies
from flask import Blueprint, render_template

from app.api.models import Pods

# Define the blueprint:
pages = Blueprint('pages', __name__, url_prefix='/pages')

@pages.route('/about/')
def return_about():
    me = Pods.query.all()[0]
    return render_template("pages/about.html", name=me.name)

app/search/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, send_from_directory

# Import the database object from the main app module
from app.api.models import Urls,Pods
from app.search import score_pages

# Import utilities
import re

# Define the blueprint:
search = Blueprint('search', __name__, url_prefix='')


def get_cached_urls(urls):
    urls_with_cache = urls
    for u in urls_with_cache:
        cache = re.sub(r"http\:\/\/|https\:\/\/", "", u[0])
        if cache[-5:] != ".html":
            cache += ".html"
        print(cache)
        u.append(cache)
    return urls_with_cache


@search.route('/')
@search.route('/index')
def index():
    '''Check whether DS has been updated.'''
    # if DS_M.shape[0] != len(Urls.query.all()):
    #    mk_matrix_from_db()
    results = []
    internal_message = ""
    query = request.args.get('q')
    print(request, request.args, query)
    num_entries = len(Urls.query.all())
    me = Pods.query.all()[0]
    if not query:
        return render_template("search/index.html", num_entries=num_entries, name=me.name, description=me.description)
    else:
        results = []
        query = query.lower()
        pears = ['0.0.0.0']
        results, pods = score_pages.run(query, pears)
        return render_template('search/results.html', pears=pears, query=query, results=results[:20], num_entries=num_entries, name=me.name, description=me.description)


@search.route('/html_cache/<path:filename>')
def custom_static(filename):
    return send_from_directory('html_cache', filename)

app/templates/pages/about.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png')}}">
        <link href="{{ url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
        <title>PeARS - {{name}}</title>
    </head>

    <body style="background-image: url('/static/background.png'); background-color:#000000; background-size:100%; background-repeat:no-repeat; background-position:fixed; top:0; left:0;">
    <nav class="navbar navbar-default" style="background-color: #000000;">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div style="padding-left:20px">
          <a href="{{url_for('search.index')}}"><img src="/static/pears-logo-small-inverse.png" height="80px"></a>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
        <li><a href="{{url_for('pages.return_about')}}">About</a></li>
        </ul>
        </div>
    </div>
    </nav>

    <div class="container">

        <div  class="row">
            <div class="col-md-6">
            <div style="background-color:#fff; color:#000; padding:20px;  border-radius:5px">
            <hr>
            <h3>What is PeARS?</h3>
            <hr>
            PeARS (Peer-to-peer Agent for Reciprocated Search) is a search engine that you can run locally from your browser. It allows you to 'index' pages (i.e. to produce a computer-readable representation of the pages' content, essential to the search process), and to search pages that you or your friends have indexed. Search happens entirely on your machine, meaning that no one knows what you are searching and when. Want to know more? Visit the website at <a href="https://pearsearch.org/index.html">https://pearsearch.org/index.html</a> and install PeARS Orchard from <a href="https://github.com/PeARSearch/PeARS-orchard">GitHub</a>.<br><br>
            <hr>
            <h3>What is a pod?</h3>
            <hr>
            A PeARS pod is a searchable index of Web pages. PeARS makes it very easy to create pods to share with your friends, in the form of text files or images. If you want to really look like a search engine, however, you'll have to do a little more work. The page you are visiting now is just an example of what a PeARS pod looks like when given a fixed online presence with a URL. Feel free to create your own -- it's not that hard! If you want to know more, head over to <a href="">https://github.com/PeARSearch/PeARS-pod</a>.
            </div>
        </div>
            
       <div class="container">
            <div style="background-color: #fff; position:fixed; right:4px; bottom:4px; border-radius:3px; padding: 3px" class="btn btn-lg" data-toggle="popover" title="<b>Background image</b>" data-content="<a href='https://www.flickr.com/photos/alanandanders/3975295765/'>tolmer</a> by <br>Flickr user Alan Lam - <a href='https://creativecommons.org/licenses/by-nd/2.0/'>CC-BY-ND 2.0</a>" data-placement="top" data-html="true">
                <img src="/static/camera_lens.png" width="30px"/><b> Credit</b>
            </div>
       </div>

       <script>
       $(document).ready(function(){
       $('[data-toggle="popover"]').popover({container: 'body'});   
       });
       </script>

    </div><!-- /.container -->
    </body>
</html>

app/templates/search/index.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png')}}">
        <link href="{{ url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
        <title>PeARS - {{name}}</title>
    </head>

    <body style="background-image: url('/static/background.png'); background-color:#000000; background-size:100%; background-repeat:no-repeat; background-position:fixed; top:0; left:0;">
    <nav class="navbar navbar-default" style="background-color: #000000;">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div style="padding-left:20px">
          <a href="{{url_for('.index')}}"><img src="/static/pears-logo-small-inverse.png" height="80px"></a>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
        <li><a href="{{url_for('pages.return_about')}}">About</a></li>
        </ul>
        </div>
    </div>
    </nav>

    <div class="container">

        <div  class="row">
            <div class="col-md-6">
            <br><br>
            <div style="background-color:#ffffff; padding:10px;  border-radius:5px">
            <p>Welcome to <b>{{name}}</b>! {{description}}</p>
            <p>It currently has {{num_entries}} recorded pages. You can search
            this pod using the search function below, to give yourself a feel for what is indexed.</p>
            </div>
            <br><br>
            <form class="mx-sm-6" action="{{url_for('.index')}}">
                <div class="input-group" style="width:100%; height:40px; text-align:left; margin:0 auto;">
                <input class="form-control input-lg" title="Enter your Search Query." placeholder="Enter your Search Query" type="text" name='q'>
                <span class="input-group-btn"><button class="btn btn-lg btn-primary" type="submit">Search</button></span>
                </div>
            </form>
            <br>
            </div>
            <div class="col-md-6">
            <br><br>
            <div class="container">
            <div style="background-color: #fff; position:fixed; right:4px; bottom:4px; border-radius:3px; padding: 3px" class="btn btn-lg" data-toggle="popover" title="<b>Background image</b>" data-content="<a href='https://www.flickr.com/photos/alanandanders/3975295765/'>tolmer</a> by <br>Flickr user Alan Lam - <a href='https://creativecommons.org/licenses/by-nd/2.0/'>CC-BY-ND 2.0</a>" data-placement="top" data-html="true">
                <img src="/static/camera_lens.png" width="30px"/><b> Credit</b>
            </div>
            </div>
<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover({container: 'body'});   
});
</script>

    </div><!-- /.container -->
    </body>
</html>

app/templates/search/results.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png')}}">
        <link href="{{ url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
        <title>PeARS - {{name}}</title>
    </head>

    <body style="background-image: url('/static/background.png'); background-color:#000000; background-size:100%; background-repeat:no-repeat; background-position:fixed; top:0; left:0;">
    <nav class="navbar navbar-default" style="background-color: #000000;">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div style="padding-left:20px">
          <a href="{{url_for('.index')}}"><img src="/static/pears-logo-small-inverse.png" height="80px"></a>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
        <li><a href="{{url_for('pages.return_about')}}">About</a></li>
        </ul>
        </div>
    </div>
    </nav>

    <div class="container">

        <div  class="row">
            <div class="col-md-10">
            <br><br>
            <form class="mx-sm-10" action="{{url_for('.index')}}">
                <div class="input-group" style="width:100%; height:40px; text-align:left; margin:0 auto;">
                <input class="form-control input-lg" title="Enter your Search Query." placeholder="Enter your Search Query" type="text" name='q'>
                <span class="input-group-btn"><button class="btn btn-lg btn-primary" type="submit">Search</button></span>
                </div>
            </form>
            <br>
            <div style="background-color:#ffffff; padding-left:30px; padding-top:10px; padding-right:30px;  border-radius:5px">
            <br><br>
               {% for result in results %}
                   <div>
                   <h3><a href="{{result[0]}}">{{result[1]}}</a>
                   {% if result[3] == True %}<img src="{{ url_for('static', filename='cc.png')}}" width='24px'/>{% endif %} </h3>
                   {{result[2]}} ... <!-- <a href="{{result[3]}}">Cache</a>--> <br>
                   <a href="{{result[0]}}">{{result[0]}}</a>
                   <hr>
                   </div>
               {% endfor %}
            </div>
            
        <div class="container">
            <div style="background-color: #fff; position:fixed; right:4px; bottom:4px; border-radius:3px; padding: 3px" class="btn btn-lg" data-toggle="popover" title="<b>Background image</b>" data-content="<a href='https://www.flickr.com/photos/alanandanders/3975295765/'>tolmer</a> by <br>Flickr user Alan Lam - <a href='https://creativecommons.org/licenses/by-nd/2.0/'>CC-BY-ND 2.0</a>" data-placement="top" data-html="true">
                <img src="/static/camera_lens.png" width="30px"/><b> Credit</b>
            </button>
        </div>
        <script>
        $(document).ready(function(){
        $('[data-toggle="popover"]').popover({container: 'body'});   
        });
        </script>

       </div>
    </div>
    </body>
</html>